# -*- coding: utf-8 -*-
"""fake_news_detection_BERT_MINI_PROJECT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oAFJsftrVGQSVyCBNdgQccHLidl317Ob
"""

# Dependencies should be installed via: pip install -r requirements.txt
# !pip install -q transformers datasets accelerate gradio scikit-learn seaborn matplotlib pandas
# !pip install -q kaggle

import os, re, json, pickle, time, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    get_linear_schedule_with_warmup,
)
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix, roc_auc_score, roc_curve,
)
from sklearn.utils.class_weight import compute_class_weight

warnings.filterwarnings('ignore')

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f'Using device: {DEVICE}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')

CONFIG = {
    'model_name'  : 'distilbert-base-uncased',  # Options: 'bert-base-uncased', 'roberta-base'
    'max_length'  : 512,  # Increased for longer articles
    'batch_size'  : 16,   # Reduce to 8 if you get OOM errors
    'epochs'      : 5,    # Increased from 3 for better convergence
    'lr'          : 2e-5,
    'weight_decay': 0.01,
    'warmup_ratio': 0.1,
    'val_size'    : 0.15,  # Slightly larger validation set
    'test_size'   : 0.15,
    'random_seed' : 42,
    'num_labels'  : 2,
    'early_stopping_patience': 3,  # Stop if no improvement for 3 epochs
}

torch.manual_seed(CONFIG['random_seed'])
np.random.seed(CONFIG['random_seed'])
print('Config:', json.dumps(CONFIG, indent=2))

"""Day 1–2: Dataset Understanding"""

# ============================================================================
# DATASET LOADING - Multiple Options
# ============================================================================

def load_dataset():
    """
    Load fake news dataset from multiple sources.
    Priority: Local CSV > Kaggle > HuggingFace datasets > Demo data
    """
    
    # Option 1: Try loading from local CSV file
    local_files = ['fake_news.csv', 'news.csv', 'WELFake_Dataset.csv', 'train.csv']
    for filename in local_files:
        if os.path.exists(filename):
            print(f'Loading from local file: {filename}')
            try:
                df = pd.read_csv(filename)
                # Try to identify text and label columns
                text_cols = [c for c in df.columns if 'text' in c.lower() or 'title' in c.lower() or 'content' in c.lower()]
                label_cols = [c for c in df.columns if 'label' in c.lower() or 'class' in c.lower()]
                
                if text_cols and label_cols:
                    df_clean = pd.DataFrame({
                        'text': df[text_cols[0]].astype(str),
                        'label_id': df[label_cols[0]]
                    })
                    # Normalize labels to 0 (Real) and 1 (Fake)
                    unique_labels = df_clean['label_id'].unique()
                    if len(unique_labels) == 2:
                        if set(unique_labels) == {0, 1}:
                            pass  # Already correct
                        elif set(unique_labels) == {'REAL', 'FAKE'} or set(unique_labels) == {'Real', 'Fake'}:
                            df_clean['label_id'] = df_clean['label_id'].map({'REAL': 0, 'Real': 0, 'FAKE': 1, 'Fake': 1})
                        else:
                            # Assume first unique value is Real (0), second is Fake (1)
                            label_map = {unique_labels[0]: 0, unique_labels[1]: 1}
                            df_clean['label_id'] = df_clean['label_id'].map(label_map)
                    
                    print(f'Loaded {len(df_clean)} samples from {filename}')
                    return df_clean
            except Exception as e:
                print(f'Error loading {filename}: {e}')
                continue
    
    # Option 2: Try loading from HuggingFace datasets
    try:
        print('Attempting to load from HuggingFace datasets...')
        from datasets import load_dataset as hf_load_dataset
        
        # Try GonzaloA/fake_news dataset
        dataset = hf_load_dataset('GonzaloA/fake_news', split='train')
        df = pd.DataFrame(dataset)
        
        # Map to our format
        df_clean = pd.DataFrame({
            'text': df['text'].astype(str),
            'label_id': df['label']  # 0=Real, 1=Fake
        })
        print(f'Loaded {len(df_clean)} samples from HuggingFace')
        return df_clean
    except Exception as e:
        print(f'Could not load from HuggingFace: {e}')
    
    # Option 3: Use expanded demo dataset (fallback)
    print('WARNING: Using expanded demo dataset. For better results, provide a real dataset!')
    import io
    DEMO_CSV = '''text,label_id
Scientists confirm new cancer treatment shows 90% success rate in trials,0
Government secretly adding mind control chemicals to tap water,1
Federal Reserve raises interest rates by 0.25% amid inflation concerns,0
Aliens have landed in New Mexico says anonymous source,1
New climate report shows record high global temperatures in 2023,0
Vaccines contain microchips to track your location,1
Tech giant reports record quarterly earnings beating analyst forecasts,0
Celebrity fakes death to escape IRS investigation,1
Study links regular Mediterranean diet to longer lifespan,0
Mayor caught on camera confessing to secret society membership,1
Electric vehicle adoption accelerates as battery costs fall further,0
Deep state operatives are controlling all major elections,1
New bridge construction project will create thousands of local jobs,0
BREAKING doctors are hiding simple cure for all cancers,1
University researchers discover new antibiotic that fights resistant bacteria,0
Government plans to ban cash and force digital currency on citizens,1
Stock markets close higher after positive economic data,0
NASA faked all moon landings says former employee,1
City council approves new affordable housing development plan,0
Bill Gates funding secret program to reduce world population,1
Supreme Court rules on landmark civil rights case,0
Drinking bleach cures COVID-19 says internet doctor,1
Unemployment rate drops to lowest level in five years,0
Celebrities are actually reptilian aliens in disguise,1
New study shows benefits of regular exercise for mental health,0
5G towers are spreading coronavirus through radio waves,1
Central bank announces new monetary policy measures,0
Flat Earth society gains millions of new members worldwide,1
Research team develops more efficient solar panel technology,0
Chemtrails are government mind control experiment,1
'''
    df_clean = pd.read_csv(io.StringIO(DEMO_CSV))
    print(f'Loaded {len(df_clean)} demo samples')
    return df_clean

# Load the dataset
df_raw = load_dataset()
df_raw['label'] = df_raw['label_id'].map({0: 'Real', 1: 'Fake'})
print(f'\nTotal samples loaded: {len(df_raw)} rows')
df_raw.head()

print('Label Distribution:')
print(df_raw['label'].value_counts())

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
fig.suptitle('Label Distribution', fontsize=14, fontweight='bold')
counts = df_raw['label'].value_counts()
colors = ['#2196F3', '#F44336']
axes[0].bar(counts.index, counts.values, color=colors, edgecolor='white')
axes[0].set_title('Count')
axes[1].pie(counts.values, labels=counts.index, autopct='%1.1f%%',
            colors=colors, wedgeprops={'edgecolor': 'white'})
axes[1].set_title('Proportion')
plt.tight_layout()
plt.show()

ratio = counts.max() / counts.min()
print(f'\nClass imbalance ratio: {ratio:.2f}x')
if ratio > 1.5:
    print('WARNING: Imbalance detected. Consider weighted loss (Day 8).')

df_raw['word_count'] = df_raw['text'].astype(str).str.split().str.len()
df_raw['char_count'] = df_raw['text'].astype(str).str.len()

print('Text Length by Class:')
print(df_raw.groupby('label')[['word_count','char_count']].describe().round(1))

fig, ax = plt.subplots(figsize=(9, 4))
for label, color in zip(['Real','Fake'], colors):
    ax.hist(df_raw[df_raw['label']==label]['word_count'],
            bins=20, alpha=0.6, label=label, color=color)
ax.axvline(CONFIG['max_length'], color='green', linestyle='--', label=f"max_length={CONFIG['max_length']}")
ax.set_title('Word Count Distribution'); ax.set_xlabel('Words'); ax.legend()
plt.tight_layout(); plt.show()

print('5 Sample Entries:')
print('='*70)
sample = df_raw.groupby('label').apply(lambda x: x.sample(min(3, len(x)), random_state=42)).reset_index(drop=True)
for _, row in sample.head(5).iterrows():
    print(f"  Label: [{row['label']}]")
    print(f"  Text : {str(row['text'])[:200]}")
    print('  ' + '-'*66)

def clean_text(text):
    if not isinstance(text, str): return ''
    text = re.sub(r'http\S+|www\S+', '', text)
    text = re.sub(r'\S+@\S+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df_raw['text'] = df_raw['text'].apply(clean_text)
df = df_raw.dropna(subset=['text', 'label']).copy()
df = df[df['text'].str.len() > 10].reset_index(drop=True)
print(f'After cleaning: {len(df)} samples')

"""Day 3: Tokenization & Data Preparation"""

tokenizer = AutoTokenizer.from_pretrained(CONFIG['model_name'])
print(f'Tokenizer: {CONFIG["model_name"]}')
print(f'Vocab size: {tokenizer.vocab_size:,}')

texts  = df['text'].tolist()
labels = df['label_id'].astype(int).tolist()

X_tv, X_test, y_tv, y_test = train_test_split(
    texts, labels, test_size=CONFIG['test_size'],
    stratify=labels, random_state=CONFIG['random_seed']
)
val_r = CONFIG['val_size'] / (1 - CONFIG['test_size'])
X_train, X_val, y_train, y_val = train_test_split(
    X_tv, y_tv, test_size=val_r,
    stratify=y_tv, random_state=CONFIG['random_seed']
)
print(f'Train: {len(X_train)}  |  Val: {len(X_val)}  |  Test: {len(X_test)}')

def tokenize(texts):
    return tokenizer(
        texts, max_length=CONFIG['max_length'],
        padding='max_length', truncation=True,
        return_attention_mask=True, return_token_type_ids=False,  # DistilBERT doesn't use token_type_ids
    )

print('Tokenizing...')
train_enc = tokenize(X_train)
val_enc   = tokenize(X_val)
test_enc  = tokenize(X_test)
print('Done!')

print('\nExample tokenized output (index 0):')
ids    = train_enc['input_ids'][0]
tokens = tokenizer.convert_ids_to_tokens(ids)
non_pad = sum(1 for m in train_enc['attention_mask'][0] if m == 1)
print(f'  Non-padding tokens : {non_pad}')
print(f'  First 15 tokens    : {tokens[:15]}')

print(f'\nInput tensor shapes:')
for split, enc in [('Train', train_enc), ('Val', val_enc), ('Test', test_enc)]:
    n, s = len(enc['input_ids']), len(enc['input_ids'][0])
    print(f'  {split:6s}  input_ids: ({n}, {s})')

class FakeNewsDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels    = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

train_dataset = FakeNewsDataset(train_enc, y_train)
val_dataset   = FakeNewsDataset(val_enc,   y_val)
test_dataset  = FakeNewsDataset(test_enc,  y_test)

train_loader = DataLoader(train_dataset, batch_size=CONFIG['batch_size'], shuffle=True)
val_loader   = DataLoader(val_dataset,   batch_size=CONFIG['batch_size'], shuffle=False)
test_loader  = DataLoader(test_dataset,  batch_size=CONFIG['batch_size'], shuffle=False)

print(f'DataLoaders ready: {len(train_loader)} train batches, {len(val_loader)} val batches')

"""Day 4–5: Model Fine-Tuning"""

model = AutoModelForSequenceClassification.from_pretrained(
    CONFIG['model_name'],
    num_labels=2,
    id2label={0: 'Real', 1: 'Fake'},
    label2id={'Real': 0, 'Fake': 1},
)
model.to(DEVICE)

total     = sum(p.numel() for p in model.parameters())
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f'Model   : {CONFIG["model_name"]}')
print(f'Params  : {total:,}  (trainable: {trainable:,})')

optimizer    = AdamW(model.parameters(), lr=CONFIG['lr'], weight_decay=CONFIG['weight_decay'])
total_steps  = len(train_loader) * CONFIG['epochs']
warmup_steps = int(total_steps * CONFIG['warmup_ratio'])
scheduler    = get_linear_schedule_with_warmup(optimizer, warmup_steps, total_steps)
print(f'Total training steps: {total_steps}  |  Warmup steps: {warmup_steps}')

def train_epoch(model, loader, optimizer, scheduler):
    model.train()
    total_loss, preds_all, labels_all = 0.0, [], []
    for batch in loader:
        ids  = batch['input_ids'].to(DEVICE)
        mask = batch['attention_mask'].to(DEVICE)
        lbls = batch['labels'].to(DEVICE)
        kw   = {'input_ids': ids, 'attention_mask': mask, 'labels': lbls}
        # DistilBERT doesn't use token_type_ids
        optimizer.zero_grad()
        out = model(**kw)
        out.loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step(); scheduler.step()
        total_loss += out.loss.item()
        preds_all.extend(torch.argmax(out.logits, 1).cpu().numpy())
        labels_all.extend(lbls.cpu().numpy())
    return total_loss / len(loader), accuracy_score(labels_all, preds_all)

@torch.no_grad()
def eval_epoch(model, loader):
    model.eval()
    total_loss, preds_all, labels_all = 0.0, [], []
    for batch in loader:
        ids  = batch['input_ids'].to(DEVICE)
        mask = batch['attention_mask'].to(DEVICE)
        lbls = batch['labels'].to(DEVICE)
        kw   = {'input_ids': ids, 'attention_mask': mask, 'labels': lbls}
        # DistilBERT doesn't use token_type_ids
        out = model(**kw)
        total_loss += out.loss.item()
        preds_all.extend(torch.argmax(out.logits, 1).cpu().numpy())
        labels_all.extend(lbls.cpu().numpy())
    return total_loss / len(loader), accuracy_score(labels_all, preds_all)


history = []
best_val_acc = 0.0
patience_counter = 0
os.makedirs('/content/models', exist_ok=True)

print(f'\nStarting training for {CONFIG["epochs"]} epochs...')
print(f'Early stopping patience: {CONFIG["early_stopping_patience"]} epochs\n')

for epoch in range(1, CONFIG['epochs'] + 1):
    t0 = time.time()
    tr_loss, tr_acc = train_epoch(model, train_loader, optimizer, scheduler)
    vl_loss, vl_acc = eval_epoch(model, val_loader)
    elapsed = time.time() - t0

    print(f'Epoch {epoch}/{CONFIG["epochs"]} | '
          f'Train Loss: {tr_loss:.4f} Acc: {tr_acc:.4f} | '
          f'Val Loss: {vl_loss:.4f} Acc: {vl_acc:.4f} | '
          f'{elapsed:.0f}s')

    history.append({'epoch': epoch, 'train_loss': tr_loss, 'train_acc': tr_acc,
                    'val_loss': vl_loss, 'val_acc': vl_acc})

    # Early stopping logic
    if vl_acc > best_val_acc:
        best_val_acc = vl_acc
        patience_counter = 0
        model.save_pretrained('/content/models/best_model')
        tokenizer.save_pretrained('/content/models/best_model')
        print(f'  [SAVED] Best model (val_acc={best_val_acc:.4f})')
    else:
        patience_counter += 1
        print(f'  No improvement ({patience_counter}/{CONFIG["early_stopping_patience"]})')
        
        if patience_counter >= CONFIG['early_stopping_patience']:
            print(f'\nEarly stopping triggered after {epoch} epochs')
            break

print(f'\nTraining complete! Best Val Accuracy: {best_val_acc:.4f}')

epochs    = [h['epoch']     for h in history]
tr_losses = [h['train_loss'] for h in history]
vl_losses = [h['val_loss']   for h in history]
tr_accs   = [h['train_acc']  for h in history]
vl_accs   = [h['val_acc']    for h in history]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
fig.suptitle('Training History', fontsize=13, fontweight='bold')
ax1.plot(epochs, tr_losses, 'b-o', label='Train', linewidth=2)
ax1.plot(epochs, vl_losses, 'r-o', label='Val',   linewidth=2)
ax1.set_title('Loss'); ax1.set_xlabel('Epoch'); ax1.legend(); ax1.grid(alpha=0.3)
ax2.plot(epochs, tr_accs, 'b-o', label='Train', linewidth=2)
ax2.plot(epochs, vl_accs, 'r-o', label='Val',   linewidth=2)
ax2.set_title('Accuracy'); ax2.set_xlabel('Epoch'); ax2.legend(); ax2.grid(alpha=0.3)
plt.tight_layout(); plt.show()

"""Day 6: Evaluation"""

@torch.no_grad()
def get_predictions(model, loader):
    model.eval()
    all_labels, all_preds, all_probs = [], [], []
    for batch in loader:
        ids  = batch['input_ids'].to(DEVICE)
        mask = batch['attention_mask'].to(DEVICE)
        kw   = {'input_ids': ids, 'attention_mask': mask}
        # DistilBERT doesn't use token_type_ids
        out   = model(**kw)
        probs = torch.softmax(out.logits, 1).cpu().numpy()
        all_preds.extend(np.argmax(probs, 1))
        all_probs.extend(probs[:, 1])
        all_labels.extend(batch['labels'].numpy())
    return np.array(all_labels), np.array(all_preds), np.array(all_probs)

y_true, y_pred, y_probs = get_predictions(model, test_loader)
print('Inference complete.')

print('Classification Report:')
print('='*60)
print(classification_report(y_true, y_pred, target_names=['Real','Fake'], digits=4))

cm = confusion_matrix(y_true, y_pred)
cm_norm = cm.astype(float) / cm.sum(axis=1, keepdims=True)

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
fig.suptitle('Confusion Matrix', fontsize=14, fontweight='bold')
for ax, data, fmt, title in zip(axes, [cm, cm_norm], ['d', '.2%'], ['Raw Counts', 'Normalised']):
    sns.heatmap(data, annot=True, fmt=fmt, cmap='Blues',
                xticklabels=['Real','Fake'], yticklabels=['Real','Fake'],
                ax=ax, linewidths=0.5, linecolor='white')
    ax.set_title(title); ax.set_xlabel('Predicted'); ax.set_ylabel('Actual')
plt.tight_layout(); plt.show()

""" Day 7: Error Analysis"""

preds_df = pd.DataFrame({
    'text'      : X_test,
    'true_label': ['Real' if l==0 else 'Fake' for l in y_true],
    'pred_label': ['Real' if p==0 else 'Fake' for p in y_pred],
    'fake_prob' : y_probs.round(4),
    'correct'   : y_true == y_pred,
})

errors = preds_df[~preds_df['correct']].copy()
errors['error_type'] = errors.apply(
    lambda r: 'FP (Real→Fake)' if r['true_label']=='Real' else 'FN (Fake→Real)', axis=1
)

print(f'Total errors: {len(errors)} / {len(preds_df)} ({len(errors)/len(preds_df)*100:.1f}%)')
print(f"\nError type breakdown:\n{errors['error_type'].value_counts()}")

print('\nTop 5 High-Confidence Errors:')
print('='*70)
for i, (_, row) in enumerate(errors.sort_values('fake_prob', ascending=False).head(5).iterrows(), 1):
    print(f'[{i}] {row["error_type"]}  (P(Fake)={row["fake_prob"]:.3f})')
    print(f'    {str(row["text"])[:200]}')
    print()

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle('Error Analysis', fontsize=13, fontweight='bold')


for correct, color, lbl in [(True,'#2196F3','Correct'),(False,'#F44336','Incorrect')]:
    axes[0].hist(preds_df[preds_df['correct']==correct]['fake_prob'],
                 bins=20, alpha=0.6, color=color, label=lbl)
axes[0].axvline(0.5, color='black', linestyle='--', label='Decision boundary')
axes[0].set_title('Confidence Distribution'); axes[0].legend()


ec = errors['error_type'].value_counts()
axes[1].bar(ec.index, ec.values, color=['#FF7043','#FFA726'], edgecolor='white')
axes[1].set_title('Error Types')
for i, v in enumerate(ec.values):
    axes[1].text(i, v+0.1, str(v), ha='center', fontweight='bold')

plt.tight_layout(); plt.show()

"""Day 8: Model Improvement – Weighted Loss"""

classes = np.unique(y_train)
weights = compute_class_weight('balanced', classes=classes, y=y_train)
wt = torch.tensor(weights, dtype=torch.float).to(DEVICE)
print(f'Class weights: Real={weights[0]:.4f}, Fake={weights[1]:.4f}')

model_wt = AutoModelForSequenceClassification.from_pretrained(CONFIG['model_name'], num_labels=2)
model_wt.to(DEVICE)
opt_wt = AdamW(model_wt.parameters(), lr=CONFIG['lr'], weight_decay=0.01)
sch_wt = get_linear_schedule_with_warmup(opt_wt, warmup_steps, total_steps)
loss_fn = nn.CrossEntropyLoss(weight=wt)

wt_history = []
for epoch in range(1, CONFIG['epochs'] + 1):
    model_wt.train()
    for batch in train_loader:
        ids = batch['input_ids'].to(DEVICE); mask = batch['attention_mask'].to(DEVICE)
        lbls = batch['labels'].to(DEVICE)
        kw = {'input_ids': ids, 'attention_mask': mask}
        # DistilBERT doesn't use token_type_ids
        opt_wt.zero_grad()
        out = model_wt(**kw)
        loss = loss_fn(out.logits, lbls)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model_wt.parameters(), 1.0)
        opt_wt.step(); sch_wt.step()
    vl_loss, vl_acc = eval_epoch(model_wt, val_loader)
    wt_history.append({'epoch': epoch, 'val_acc': vl_acc})
    print(f'Weighted | Epoch {epoch} | Val Acc: {vl_acc:.4f}')


print('\nComparison:')
print(f'  Baseline (no weighting) : {history[-1]["val_acc"]:.4f}')
print(f'  Weighted loss           : {wt_history[-1]["val_acc"]:.4f}')

"""Day 9: Deployment with Gradio"""

import gradio as gr

deploy_model = AutoModelForSequenceClassification.from_pretrained('/content/models/best_model')
deploy_tok   = AutoTokenizer.from_pretrained('/content/models/best_model')
deploy_model.eval().to(DEVICE)

@torch.no_grad()
def classify_news(text):
    if not text.strip():
        return 'WARNING: Please enter some text.'
    inputs = deploy_tok(text, max_length=CONFIG['max_length'], padding='max_length',
                        truncation=True, return_tensors='pt')
    inputs = {k: v.to(DEVICE) for k, v in inputs.items()
              if k in ('input_ids', 'attention_mask')}  # DistilBERT doesn't use token_type_ids
    out   = deploy_model(**inputs)
    probs = torch.softmax(out.logits, 1).cpu().numpy()[0]
    pred  = np.argmax(probs)
    label = 'REAL' if pred == 0 else 'FAKE'
    conf  = probs[pred] * 100
    marker = '[REAL]' if pred == 0 else '[FAKE]'
    return f"{marker} **{label}** (confidence: {conf:.1f}%)\n\nReal: {probs[0]*100:.1f}%  |  Fake: {probs[1]*100:.1f}%"

demo = gr.Interface(
    fn=classify_news,
    inputs=gr.Textbox(label='News Headline or Article', lines=5,
                      placeholder='Paste news text here...'),
    outputs=gr.Markdown(label='Result'),
    title='Fake News Detector',
    description='Fine-tuned BERT / DistilBERT model to classify news as Real or Fake.',
    examples=[
        ['Scientists confirm new cancer treatment shows 90% success in trials.'],
        ['Government secretly adding mind control chemicals to tap water!'],
        ['Federal Reserve raises interest rates by 0.25% amid inflation concerns.'],
    ],
    theme=gr.themes.Soft(),
)

demo.launch(share=True)